### ISSUE TITLE
Got failed Jobs when using

### ISSUE THREAD

**Issue by no1melman** [soomo/jest-check#1]
First of all, this is a great action - so thanks for creating it.

I've ran this and I get failed jobs and the output looks like:

❌ CreateLocation tests (4.215s ⏱️)
 - ✅ should list all files
 - ✅ should list all files and sub dirs with files
 - ✅ should list all files and sub dirs with files
 - ✅ should make the dir

❌ undefined (0.249s ⏱️)
 - ✅ adds 1 + 2 to equal 3

After reading your code, I can only assume that this might be the issue, when compared to my json which has `"status": "passed"` on each `assertionResults`, the logic in the formatter seems to be fine.

https://github.com/soomo/jest-check/blob/03bbd224b19f83f29298c1d41a08d4c5800d3c1a/src/index.ts#L36-L41

**Comment by no1melman** [comment]
I forked your repo - it seems to be working as expected, so don't know what's gone wrong in the github CI

**Comment by no1melman** [comment]
would it not be better to pull `conclusion` from `summary.success` aka, the top level of the output file:

```
{
  "numFailedTestSuites": 0,
  "numFailedTests": 0,
  "numPassedTestSuites": 2,
  "numPassedTests": 5,
  "numPendingTestSuites": 0,
  "numPendingTests": 0,
  "numRuntimeErrorTestSuites": 0,
  "numTodoTests": 0,
  "numTotalTestSuites": 2,
  "numTotalTests": 5,
  "openHandles": [],
  "snapshot": {
    "added": 0,
    "didUpdate": false,
    "failure": false,
    "filesAdded": 0,
    "filesRemoved": 0,
    "filesRemovedList": [],
    "filesUnmatched": 0,
    "filesUpdated": 0,
    "matched": 0,
    "total": 0,
    "unchecked": 0,
    "uncheckedKeysByFile": [],
    "unmatched": 0,
    "updated": 0
  },
  "startTime": 1678809953594,
  "success": true,
```

**Comment by no1melman** [comment]
Also wonder whether it might be useful to put in some `core.debug()` statements in and around

**Comment by no1melman** [comment]
Okay - so the problem was the version, I just used what was on the `README.md` which states `0.0.1`, should have been using `0.0.5`

**Comment by bkwhite** [comment]
Updated the README. Good catch!
